substitutions:
  _REGISTRY: us.gcr.io
  _IMAGE: cromwell-task-monitor-bq

steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  dir: monitor
  args:
  - -c
  - |
    set -e
    export IMAGE=${_REGISTRY}/${PROJECT_ID}/${_IMAGE}
    docker build -t $${IMAGE} .
    docker push $${IMAGE}
