substitutions:
  _REGION: us-east1
  _DATASET_ID: cromwell_monitoring
  _CROMWELL_BASEURL: '' # e.g. https://cromwell.example.org
  _CROMWELL_SAM_BASEURL: '' # e.g. https://sam.example.org
  _CROMWELL_LOGS_BUCKET: '' # e.g. project-cromwell-logs
  _CROMWELL_TASK_SERVICE_ACCOUNT_EMAIL: '' # e.g. cromwell-task@project.iam.gserviceaccount.com

steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  dir: deploy
  env:
  - PROJECT_ID=${PROJECT_ID}
  - DATASET_ID=${_DATASET_ID}
  args:
  - ./docker.sh

- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  dir: deploy
  env:
  - REGION=${_REGION}
  - DATASET_ID=${_DATASET_ID}
  - CROMWELL_BASEURL=${_CROMWELL_BASEURL}
  - CROMWELL_SAM_BASEURL=${_CROMWELL_SAM_BASEURL}
  - CROMWELL_LOGS_BUCKET=${_CROMWELL_LOGS_BUCKET}
  - CROMWELL_TASK_SERVICE_ACCOUNT_EMAIL=${_CROMWELL_TASK_SERVICE_ACCOUNT_EMAIL}
  args:
  - ./gcloud.sh
